name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  server-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH with agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa; ssh-keyscan github.com >> ~/.ssh/known_hosts'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ~/.ssh/project-spring
            git pull origin main
            cd topgunFinal
            mvn clean package -DskipTests
            sudo fuser -k -n tcp 8080 || true
            java -Duser.timezone=Asia/Seoul -jar target/*SNAPSHOT.war > ./output.log 2>&1 &