name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Debug SSH Key
        run: |
          echo "SSH key debug:"
          ssh-add -l
          ssh-add -D  # 모든 키 제거
          ssh-add -k ~/.ssh/id_rsa  # SSH 키 추가

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd ~/.ssh/project-spring
            git pull origin main
            cd topgunFinal
            mvn clean package -DskipTests
            sudo fuser -k -n tcp 8080 || true
            java -Duser.timezone=Asia/Seoul -jar target/*SNAPSHOT.war > ./output.log 2>&1 &
          EOF